development:
  adapter: postgresql
  encoding: unicode
  database: myflix_development
  pool: 5
  host: host.docker.internal
  username: postgres
  password:
  port: 9999

test:
  adapter: postgresql
  encoding: unicode
  database: myflix_test
  pool: 5
  host: host.docker.internal
  username: postgres
  password:
  port: 9999
